import { v4 as uuidv4 } from "uuid";

export const TaskData = [
  {
    id: uuidv4(),
    title: "Create Dashboard",
    taskdate: "09/01/21",
    Status: "to do",
    done: "2",
    taskcount: "10",
  },
  {
    id: uuidv4(),
    title: "Create Task List",
    taskdate: "08/22/21",
    status: "in progress",
    done: "3",
    taskcount: "4",
  },
  {
    id: uuidv4(),
    title: "Create Sidebar",
    taskdate: "08/21/21",
    status: "done",
    done: "1",
    taskcount: "1",
  },
  {
    id: uuidv4(),
    title: "Upload to Github",
    taskdate: "08/20/21",
    status: "done",
    done: "1",
    taskcount: "1",
  },
  {
    id: uuidv4(),
    title: "Style Task List",
    taskdate: "08/21/21",
    status: "done",
    done: "1",
    taskcount: "1",
  },
  {
    id: uuidv4(),
    title: "Create Task",
    taskdate: "08/23/21",
    status: "to do",
    done: "0",
    taskcount: "1",
  },
  {
    id: uuidv4(),
    title: "Fix Side bar positioning",
    taskdate: "09/02/21",
    status: "to do",
    done: "0",
    taskcount: "1",
  },
  {
    id: uuidv4(),
    title: "Add unique key to task list",
    taskdate: "08/24/21",
    status: "done",
    done: "1",
    taskcount: "1",
  },
  //   {
  //     id: uuidv4(),
  //     title: "done task 1",
  //     taskdate: "08/24/21",
  //     status: "done",
  //     done: "1",
  //     taskcount: "1",
  //   },
  //   {
  //     id: uuidv4(),
  //     title: "done task 2",
  //     taskdate: "08/24/21",
  //     status: "done",
  //     done: "1",
  //     taskcount: "1",
  //   },
  //   {
  //     id: uuidv4(),
  //     title: "done task 3",
  //     taskdate: "08/24/21",
  //     status: "done",
  //     done: "1",
  //     taskcount: "1",
  //   },
  //   {
  //     id: uuidv4(),
  //     title: "done task 4",
  //     taskdate: "08/24/21",
  //     status: "done",
  //     done: "1",
  //     taskcount: "1",
  //   },
  //   {
  //     id: uuidv4(),
  //     title: "done task 5",
  //     taskdate: "08/24/21",
  //     status: "done",
  //     done: "1",
  //     taskcount: "1",
  //   },
  //   {
  //     id: uuidv4(),
  //     title: "done task 6",
  //     taskdate: "08/24/21",
  //     status: "done",
  //     done: "1",
  //     taskcount: "1",
  //   },
  //   {
  //     id: uuidv4(),
  //     title: "done task 7",
  //     taskdate: "08/24/21",
  //     status: "done",
  //     done: "1",
  //     taskcount: "1",
  //   },
  //   {
  //     id: uuidv4(),
  //     title: "done task 8",
  //     taskdate: "08/24/21",
  //     status: "done",
  //     done: "1",
  //     taskcount: "1",
  //   },
];
